aliases:
    fleeks: cd ~/.local/share/fleek
    ca: chezmoi add
    ce: chezmoi edit --apply
    cu: chezmoi update
    cc: chezmoi cd
    cf: chezmoi forget
    ci: chezmoi init
    cr: chezmoi re-add
    df : duf
    ducks : du -chs * 2>/dev/null | sort -rh | head -11
    htop : glances
    pdo: podman images | awk '{print \$3,\$2}' | grep '<none>' | awk '{print \$1}' | xargs -t podman rmi 
    pdi: podman images
    pdr: podman rmi
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - chezmoi
    - glances
    - python3Full
    - poetry
    - poppler_utils
    - restic
    - pv
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: ironman-laptop
      os: linux
      username: ironman
track: nixos-unstable
unfree: true
users:
    - email: 29488820+ironman820@users.noreply.github.com
      name: Nicholas Eastman
      ssh_private_key_file: ~/.ssh/github_home
      ssh_public_key_file: ~/.ssh/github_home.pub
      username: ironman
